### PR TITLE
Adding passthroughURL to allow all requests for URL to be passed through

### PR DESCRIPTION
**Pull request by step2yeung**
In our tests, we need to send an URL request out to a express server. With pretender as it is currently, we do not have a way to to do this.
This flag would allow URL requests to be passed through.

### CODE REVIEW

**Comment by trek** [comment]
Can you explain a bit how this is different than the existing passthrough behaviors?

**Comment by step2yeung** [comment]
Sure, I added this to deal with fully qualified URLs. Since pretender only handle requests to paths, in checkPassthrough, my requests will fail at 'throwIfURLDetected' since it is a fully qualified URLs.

I think in the spirit of pretender, this change will still respect the basis of only handling requests to path, while allowing anything with fully qualified URLs to go thru if required.

**Comment by trek** [comment]
Even if https://github.com/trek/pretender/pull/66 is merged?

**Comment by step2yeung** [comment]
Thanks Trek, that PR is exactly that's needed.

**Comment by trek** [comment]
Ok, closing in favor of #66 then

**Pull request closed without merging**
