### PR TITLE
Add latency parameter to server

### PR DESCRIPTION
**Pull request by samselikoff**
I'm starting to use pretender as my fake server for clicking around my apps. Having the ability to simulate latency (like in Ember Fixture adapter) would be great.

### CODE REVIEW

**Comment by trek** [comment]
this is handled by #48?

**Comment by samselikoff** [comment]
Ah - Yep!

**Comment by trek** [comment]
#48 is now on master/0.5.0

**Comment by samselikoff** [comment]
thanks for your work trek!

**Comment by trek** [comment]
This one was all @DingoEatingFuzz

**Comment by samselikoff** [comment]
well, thanks for maintaining, and thanks for all your work @DingoEatingFuzz ! :D

**Comment by DingoEatingFuzz** [comment]
:beers:

**Pull request closed without merging**
